version: '3.9'

services:
  web:
    build: .
    command: gunicorn stocks_products.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000

    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Shambala
      - POSTGRES_DB=netology_stocks_products

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
    volumes:
      - ./static:/static

volumes:
  postgres_data: